name: Release-Mastodon

on:
  workflow_call:
    secrets:
      MASTODON_URL:
        required: true
      MASTODON_ACCESS_TOKEN:
        required: true

  release:
    types:
      - published

jobs:
  notify:
    name: Mastodon
    runs-on: ubuntu-latest
    steps:
      - name: Trim Body
        shell: bash
        run: |
          echo "BODY=$(echo "${{ github.event.release.body }}" | cut -c1-350 )" >> $GITHUB_ENV
      - name: Send toot to Mastodon
        continue-on-error: true
        id: mastodon
        uses: cbrgm/mastodon-github-action@v1
        env:
          REPOSITORY: ${{ github.repository }}
          REPOSITORY_URL: ${{ github.repository.html_url }}
          REF: ${{ github.ref_name }}
          BODY: ${{ github.env.BODY }}
          LINK: ${{ github.event.release.html_url }}
          TITLE: ${{ github.event.release.name }}
          REPO_URL: ${{ github.event.release.repository.html_url }}
          REPO_NAME: ${{ github.event.release.repository.full_name }}
          MASTODON_URL: ${{ secrets.MASTODON_URL }}
          MASTODON_ACCESS_TOKEN: ${{ secrets.MASTODON_ACCESS_TOKEN }}
        with:
          message: |
            ${{ env.REPOSITORY }} released a new version.
            ${{ env.TITLE }} is out now! 
            
            ${{ env.BODY }}
            ${{ env.LINK }}
            
            ${{ env.REPO_URL }}
          visibility: "public"

